### ISSUE TITLE
Signature Maintenance

### ISSUE THREAD

**Issue by gibbs** [JamesDooley/VersionFinder#1]
Hi. How is the signature file maintained? Do you manually manage it?

**Comment by JamesDooley** [comment]
The signatures file is updated via a script on my workstation, currently it is a manual process for running the script.  Eventually I will likely change it to run every night once I can be sure there are no major bugs.

**Comment by gibbs** [comment]
Any chance of that getting added to this repo?

**Comment by JamesDooley** [comment]
I can see about cleaning it up a bit and push it to a branch.
It does require perl 5.10.1+, since it relies on Mojo::UserAgent to easily pull from all of the remote sites.

**Comment by JamesDooley** [comment]
I added the updated script to the main repo.
As mentioned before it does require Mojo::UserAgent which requires Perl 5.10.1+
It also requires Hash::Merge, everything else should be Core.

If it is in the directory that the .vf_signatures file exists in (ie just do a git pull) it will automatically detect the signatures file and check for updated signatures.

If you provide --update it will not prompt for changes and just update the signatures file.  If the CMS sites themselves update, it is possible it will not pull the versions, in which case it will return an error and not update.

If you run in to any problems with the script let me know.

**Comment by JamesDooley** [comment]
Looks like the script did not get pushed the first time, I confirmed it in the repo now.

**Comment by gibbs** [comment]
Thanks for the good work.
