### ISSUE TITLE
Joomla 3.7.3 update

### ISSUE THREAD

**Issue by bettinz** [JamesDooley/VersionFinder#7]
Hello, with Joomla 3.7.3 I can't see version number, all sites are under:
==== Unable to Determine Version Number ====

Thanks :-)

**Comment by JamesDooley** [comment]
This should be fixed with the latest commit.
It looks like they moved the version information from version.php to an xml file at some point.

If your signature file does not update, you can force an update by running
`versionfinder --update`

**Comment by bettinz** [comment]
Thank you very much :-)
